version: '3'

services:
  tiktok-scraper:
    build: .
    container_name: tiktok-scraper
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
    env_file:
      - .env 